stages:
  - test
  - build

stage_test:
  stage: test
  image: node:lts-alpine
  tags:
    - docker
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run prettier:check
    - npm run lint:ts
  allow_failure: false

stage_build:
  stage: build
  tags:
    - test
  script:
    - npm ci --production --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "dist/"
    untracked: false
    when: on_success
    expire_in: 1 days
